package org.example.service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;

/**
 * Meeting service: Jitsi Meet link generation + AI meeting report from raw text.
 */
public class MeetingService {

    private static final String JITSI_BASE = "https://meet.jit.si/";

    /**
     * Generate a Jitsi Meet link for a meeting.
     * No API key required — Jitsi is free and open.
     */
    public String generateJitsiLink(String projectTitle, int meetingId) {
        // Sanitize: remove spaces and special chars
        String room = "SmartPFE-" + sanitize(projectTitle) + "-" + meetingId;
        return JITSI_BASE + room;
    }

    /**
     * Generate a meeting report from raw text using NLP-style extraction.
     * Extracts: participants, decisions, action items, next steps.
     */
    public String generateMeetingReport(String rawText, String meetingTitle, String projectTitle) {
        if (rawText == null || rawText.isBlank()) {
            return "No meeting notes provided.";
        }

        StringBuilder report = new StringBuilder();
        report.append("═══════════════════════════════════════\n");
        report.append("         MEETING REPORT\n");
        report.append("═══════════════════════════════════════\n");
        report.append("Title:   ").append(meetingTitle != null ? meetingTitle : "Meeting").append("\n");
        report.append("Project: ").append(projectTitle != null ? projectTitle : "-").append("\n");
        report.append("Date:    ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"))).append("\n");
        report.append("───────────────────────────────────────\n\n");

        // Extract participants (names after "present:", "attendees:", "participants:")
        List<String> participants = extractParticipants(rawText);
        if (!participants.isEmpty()) {
            report.append("PARTICIPANTS:\n");
            participants.forEach(p -> report.append("  • ").append(p).append("\n"));
            report.append("\n");
        }

        // Extract decisions (sentences with "decided", "agreed", "approved", "will")
        List<String> decisions = extractSentencesByKeywords(rawText,
            List.of("decided", "agreed", "approved", "confirmed", "validated"));
        if (!decisions.isEmpty()) {
            report.append("DECISIONS MADE:\n");
            decisions.forEach(d -> report.append("  ✓ ").append(d).append("\n"));
            report.append("\n");
        }

        // Extract action items (sentences with "todo", "action", "must", "should", "will", "need to")
        List<String> actions = extractSentencesByKeywords(rawText,
            List.of("todo", "action", "must", "should", "will", "need to", "assigned to", "responsible"));
        if (!actions.isEmpty()) {
            report.append("ACTION ITEMS:\n");
            actions.forEach(a -> report.append("  → ").append(a).append("\n"));
            report.append("\n");
        }

        // Extract blockers (sentences with "blocked", "issue", "problem", "risk", "concern")
        List<String> blockers = extractSentencesByKeywords(rawText,
            List.of("blocked", "issue", "problem", "risk", "concern", "obstacle", "delay"));
        if (!blockers.isEmpty()) {
            report.append("BLOCKERS / RISKS:\n");
            blockers.forEach(b -> report.append("  ⚠ ").append(b).append("\n"));
            report.append("\n");
        }

        // Extract next meeting (sentences with "next meeting", "next sprint", "follow-up")
        List<String> next = extractSentencesByKeywords(rawText,
            List.of("next meeting", "next sprint", "follow-up", "next week", "next session"));
        if (!next.isEmpty()) {
            report.append("NEXT STEPS:\n");
            next.forEach(n -> report.append("  📅 ").append(n).append("\n"));
            report.append("\n");
        }

        // Summary: word count, sentence count
        int wordCount = rawText.split("\\s+").length;
        int sentenceCount = rawText.split("[.!?]+").length;
        report.append("───────────────────────────────────────\n");
        report.append("Summary: ").append(wordCount).append(" words, ")
              .append(sentenceCount).append(" sentences processed.\n");
        report.append("Generated by SmartPFE AI Report Engine\n");
        report.append("═══════════════════════════════════════\n");

        return report.toString();
    }

    private List<String> extractParticipants(String text) {
        List<String> result = new ArrayList<>();
        // Look for patterns like "Present: Alice, Bob" or "Attendees: ..."
        Pattern p = Pattern.compile("(?i)(present|attendees?|participants?|members?)\\s*:?\\s*([^.\\n]+)");
        Matcher m = p.matcher(text);
        if (m.find()) {
            String[] names = m.group(2).split("[,;]");
            for (String name : names) {
                String clean = name.trim();
                if (!clean.isEmpty() && clean.length() < 50) result.add(clean);
            }
        }
        return result;
    }

    private List<String> extractSentencesByKeywords(String text, List<String> keywords) {
        List<String> result = new ArrayList<>();
        String[] sentences = text.split("[.!?\\n]+");
        for (String sentence : sentences) {
            String lower = sentence.toLowerCase().trim();
            if (lower.length() < 5) continue;
            for (String kw : keywords) {
                if (lower.contains(kw)) {
                    String clean = sentence.trim();
                    if (clean.length() > 5 && clean.length() < 300 && !result.contains(clean)) {
                        result.add(clean);
                    }
                    break;
                }
            }
        }
        return result.stream().limit(5).collect(Collectors.toList());
    }

    private String sanitize(String s) {
        if (s == null) return "Meeting";
        return s.replaceAll("[^a-zA-Z0-9]", "-").replaceAll("-+", "-").substring(0, Math.min(s.length(), 30));
    }
}
